import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import NavBar from "~/components/navigation-bar";
import News from "~/components/news/news";

import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Paschta;</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-bg min-h-screen">
        <NavBar></NavBar>
        <div className="flex w-full max-w-none flex-col items-center justify-center p-8">
          <span id="title" className="text-3xl font-semibold">
            {" "}
            Paschta; - Hírek{" "}
          </span>
          <News></News>
        </div>
      </main>
    </>
  );
}
