import React from "react";
import Head from "next/head";
import Link from "next/link";
import NavBar from "~/components/navigation-bar";
import News from "~/components/news/news";
import Foods from "~/components/foods";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { stat } from "fs";
function Konyha() {
  const { status } = useSession();
  const router = useRouter();

  if (status === "unauthenticated") {
    router.push("/api/auth/signin");
  }
  return (
    <>
      <Head>
        <title>Paschta;</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-[96vh] bg-bg">
        <NavBar></NavBar>
        <div className="flex w-full max-w-none flex-col items-center justify-center p-8">
          <span id="title" className="text-3xl font-semibold">
            {" "}
            Paschta; - Konyha{" "}
          </span>
          <Foods></Foods>
        </div>
      </main>
    </>
  );
}

export default Konyha;
