import React from "react";
import Head from "next/head";
import NavBar from "~/components/navigation-bar";
import Nyitaschs from "~/components/nyitaschs";

function Nyitasch() {
  return (
    <>
      <Head>
        <title>Paschta;</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-[96vh] bg-bg">
        <NavBar></NavBar>
        <div className="flex w-full max-w-none flex-col items-center justify-center p-8">
          <span id="title" className="text-3xl font-semibold">
            {" "}
            Paschta; - Nyitások{" "}
          </span>
          <Nyitaschs></Nyitaschs>
        </div>
      </main>
    </>
  );
}

export default Nyitasch;
